scan_timeout = 100
palette = "catppuccin_mocha"

format = """
[](blue)\
$os\
$username\
[](bg:lavender fg:blue)\
$directory\
[](fg:lavender bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$python\
$rust\
$golang\
$c\
$lua\
[](fg:teal)\
$character"""

right_format = ""

[os]
disabled = false
style = "bg:blue fg:crust"

[os.symbols]
Macos = ""
Linux = ""

[username]
show_always = true
style_user = "bg:blue fg:crust"
style_root = "bg:blue fg:red"
format = "[ $user ]($style)"

[directory]
style = "bg:lavender fg:crust"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = ""
style = "bg:green fg:crust"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:green fg:crust"
format = "[$all_status$ahead_behind ]($style)"

[python]
symbol = ""
style = "bg:teal fg:crust"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "bg:teal fg:crust"
format = "[ $symbol $version ]($style)"

[golang]
symbol = ""
style = "bg:teal fg:crust"
format = "[ $symbol $version ]($style)"

[c]
symbol = ""
style = "bg:teal fg:crust"
format = "[ $symbol $version ]($style)"

[lua]
symbol = ""
style = "bg:teal fg:crust"
format = "[ $symbol $version ]($style)"

[character]
success_symbol = " [](green)"
error_symbol = " [](red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
